enum IntroTextState {
	WAIT_TO_FADE_IN_MAIN_TEXT,
	FADE_IN_MAIN_TEXT,
	FADE_IN_PLAYER_PROMPT,
	AWAITING_PLAYER_INPUT,
	FADE_OUT
};

state = IntroTextState.WAIT_TO_FADE_IN_MAIN_TEXT;

TOTAL_WAIT_TO_FADE_IN_MAIN_TEXT_FRAMES = 60;
waitToFadeInMainTextFramesLeft = TOTAL_WAIT_TO_FADE_IN_MAIN_TEXT_FRAMES;

TOTAL_FADE_IN_MAIN_TEXT_FRAMES = 60;
fadeInMainTextFramesLeft = TOTAL_FADE_IN_MAIN_TEXT_FRAMES;

TOTAL_FADE_IN_PLAYER_PROMPT_FRAMES = 60;
fadeInPlayerPromptFramesLeft = TOTAL_FADE_IN_PLAYER_PROMPT_FRAMES;

TOTAL_FADE_OUT_FRAMES = 60;
fadeOutFramesLeft = TOTAL_FADE_OUT_FRAMES;

mainTextAlpha = 0;
playerPromptAlpha = 0;
